
// This file has been generated by the GUI designer. Do not modify.
namespace NebliDex_Linux
{
	public partial class PlaceOrderWindow
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.Label Order_Header;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label3;

		private global::Gtk.Label My_Balance;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label Price_Header;

		private global::Gtk.Entry Price_Input;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label Amount_Header;

		private global::Gtk.Entry Amount_Input;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label Min_Amount_Header;

		private global::Gtk.Entry Min_Amount_Input;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Label Total_Header;

		private global::Gtk.Entry Total_Input;

		private global::Gtk.HSeparator hseparator2;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.Button Order_Button;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget NebliDex_Linux.PlaceOrderWindow
			this.WidthRequest = 400;
			this.Name = "NebliDex_Linux.PlaceOrderWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Create Limit Order");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.BorderWidth = ((uint)(5));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child NebliDex_Linux.PlaceOrderWindow.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.vbox3.BorderWidth = ((uint)(5));
			// Container child vbox3.Gtk.Box+BoxChild
			this.Order_Header = new global::Gtk.Label();
			this.Order_Header.Name = "Order_Header";
			this.Order_Header.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'18\'><b>Buy NEBL</b></span>");
			this.Order_Header.UseMarkup = true;
			this.vbox3.Add(this.Order_Header);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.Order_Header]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Homogeneous = true;
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'12\'>Balance:</span>");
			this.label3.UseMarkup = true;
			this.hbox5.Add(this.label3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label3]));
			w2.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.My_Balance = new global::Gtk.Label();
			this.My_Balance.Name = "My_Balance";
			this.My_Balance.Xalign = 1F;
			this.My_Balance.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'12\'><b>0 BTC</b></span>");
			this.My_Balance.UseMarkup = true;
			this.hbox5.Add(this.My_Balance);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.My_Balance]));
			w3.Position = 1;
			this.vbox3.Add(this.hbox5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox5]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(5));
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Homogeneous = true;
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.Price_Header = new global::Gtk.Label();
			this.Price_Header.Name = "Price_Header";
			this.Price_Header.Xalign = 0F;
			this.Price_Header.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'11\'>Price (BTC):</span>");
			this.Price_Header.UseMarkup = true;
			this.hbox6.Add(this.Price_Header);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.Price_Header]));
			w5.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.Price_Input = new global::Gtk.Entry();
			this.Price_Input.WidthRequest = 150;
			this.Price_Input.CanFocus = true;
			this.Price_Input.Name = "Price_Input";
			this.Price_Input.IsEditable = true;
			this.Price_Input.InvisibleChar = '•';
			this.Price_Input.Xalign = 1F;
			this.hbox6.Add(this.Price_Input);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.Price_Input]));
			w6.Position = 1;
			this.vbox3.Add(this.hbox6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox6]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			w7.Padding = ((uint)(5));
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Homogeneous = true;
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.Amount_Header = new global::Gtk.Label();
			this.Amount_Header.Name = "Amount_Header";
			this.Amount_Header.Xalign = 0F;
			this.Amount_Header.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'11\'>Amount (NEBL):</span>");
			this.Amount_Header.UseMarkup = true;
			this.hbox7.Add(this.Amount_Header);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.Amount_Header]));
			w8.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.Amount_Input = new global::Gtk.Entry();
			this.Amount_Input.WidthRequest = 150;
			this.Amount_Input.CanFocus = true;
			this.Amount_Input.Name = "Amount_Input";
			this.Amount_Input.IsEditable = true;
			this.Amount_Input.InvisibleChar = '•';
			this.Amount_Input.Xalign = 1F;
			this.hbox7.Add(this.Amount_Input);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.Amount_Input]));
			w9.Position = 1;
			this.vbox3.Add(this.hbox7);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox7]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			w10.Padding = ((uint)(5));
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Homogeneous = true;
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.Min_Amount_Header = new global::Gtk.Label();
			this.Min_Amount_Header.Name = "Min_Amount_Header";
			this.Min_Amount_Header.Xalign = 0F;
			this.Min_Amount_Header.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'11\'>Minimum Match (NEBL):</span>");
			this.Min_Amount_Header.UseMarkup = true;
			this.hbox8.Add(this.Min_Amount_Header);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.Min_Amount_Header]));
			w11.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.Min_Amount_Input = new global::Gtk.Entry();
			this.Min_Amount_Input.WidthRequest = 150;
			this.Min_Amount_Input.CanFocus = true;
			this.Min_Amount_Input.Name = "Min_Amount_Input";
			this.Min_Amount_Input.IsEditable = true;
			this.Min_Amount_Input.InvisibleChar = '•';
			this.Min_Amount_Input.Xalign = 1F;
			this.hbox8.Add(this.Min_Amount_Input);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.Min_Amount_Input]));
			w12.Position = 1;
			this.vbox3.Add(this.hbox8);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox8]));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			w13.Padding = ((uint)(5));
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.vbox3.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hseparator1]));
			w14.Position = 5;
			w14.Expand = false;
			w14.Fill = false;
			w14.Padding = ((uint)(5));
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Homogeneous = true;
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.Total_Header = new global::Gtk.Label();
			this.Total_Header.Name = "Total_Header";
			this.Total_Header.Xalign = 0F;
			this.Total_Header.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'11\'>Total Cost (BTC):</span>");
			this.Total_Header.UseMarkup = true;
			this.hbox9.Add(this.Total_Header);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.Total_Header]));
			w15.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.Total_Input = new global::Gtk.Entry();
			this.Total_Input.WidthRequest = 150;
			this.Total_Input.CanFocus = true;
			this.Total_Input.Name = "Total_Input";
			this.Total_Input.IsEditable = true;
			this.Total_Input.InvisibleChar = '•';
			this.Total_Input.Xalign = 1F;
			this.hbox9.Add(this.Total_Input);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.Total_Input]));
			w16.Position = 1;
			this.vbox3.Add(this.hbox9);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox9]));
			w17.Position = 6;
			w17.Expand = false;
			w17.Fill = false;
			w17.Padding = ((uint)(5));
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator();
			this.hseparator2.Name = "hseparator2";
			this.vbox3.Add(this.hseparator2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hseparator2]));
			w18.Position = 7;
			w18.Expand = false;
			w18.Fill = false;
			w18.Padding = ((uint)(5));
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(100));
			this.alignment1.TopPadding = ((uint)(5));
			this.alignment1.RightPadding = ((uint)(100));
			this.alignment1.BottomPadding = ((uint)(5));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.Order_Button = new global::Gtk.Button();
			this.Order_Button.CanFocus = true;
			this.Order_Button.Name = "Order_Button";
			this.Order_Button.UseUnderline = true;
			this.Order_Button.Label = global::Mono.Unix.Catalog.GetString("Create Order");
			this.alignment1.Add(this.Order_Button);
			this.vbox3.Add(this.alignment1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.alignment1]));
			w20.Position = 8;
			w20.Expand = false;
			w20.Fill = false;
			this.Add(this.vbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 336;
			this.Show();
		}
	}
}
