
// This file has been generated by the GUI designer. Do not modify.
namespace NebliDex_Linux
{
	public partial class UserPromptWindow
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label Prompt;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Entry User_Response_Pass;

		private global::Gtk.Entry User_Response;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.Button OK_Button;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget NebliDex_Linux.UserPromptWindow
			this.WidthRequest = 325;
			this.Name = "NebliDex_Linux.UserPromptWindow";
			this.Title = "";
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.BorderWidth = ((uint)(5));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child NebliDex_Linux.UserPromptWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.Prompt = new global::Gtk.Label();
			this.Prompt.Name = "Prompt";
			this.Prompt.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Enter Prompt Here</b>");
			this.Prompt.UseMarkup = true;
			this.Prompt.Wrap = true;
			this.Prompt.Justify = ((global::Gtk.Justification)(2));
			this.vbox2.Add(this.Prompt);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.Prompt]));
			w1.Position = 0;
			w1.Padding = ((uint)(5));
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			this.hbox3.BorderWidth = ((uint)(5));
			// Container child hbox3.Gtk.Box+BoxChild
			this.User_Response_Pass = new global::Gtk.Entry();
			this.User_Response_Pass.WidthRequest = 250;
			this.User_Response_Pass.CanFocus = true;
			this.User_Response_Pass.Name = "User_Response_Pass";
			this.User_Response_Pass.IsEditable = true;
			this.User_Response_Pass.Visibility = false;
			this.User_Response_Pass.InvisibleChar = '•';
			this.hbox3.Add(this.User_Response_Pass);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.User_Response_Pass]));
			w2.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.User_Response = new global::Gtk.Entry();
			this.User_Response.WidthRequest = 250;
			this.User_Response.CanFocus = true;
			this.User_Response.Name = "User_Response";
			this.User_Response.IsEditable = true;
			this.User_Response.InvisibleChar = '•';
			this.hbox3.Add(this.User_Response);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.User_Response]));
			w3.Position = 1;
			this.vbox2.Add(this.hbox3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(5));
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.alignment2.LeftPadding = ((uint)(100));
			this.alignment2.TopPadding = ((uint)(5));
			this.alignment2.RightPadding = ((uint)(100));
			this.alignment2.BottomPadding = ((uint)(10));
			// Container child alignment2.Gtk.Container+ContainerChild
			this.OK_Button = new global::Gtk.Button();
			this.OK_Button.CanFocus = true;
			this.OK_Button.Name = "OK_Button";
			this.OK_Button.UseUnderline = true;
			this.OK_Button.Label = global::Mono.Unix.Catalog.GetString("Ok");
			this.alignment2.Add(this.OK_Button);
			this.vbox2.Add(this.alignment2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment2]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.User_Response.Hide();
			this.Show();
		}
	}
}
