
// This file has been generated by the GUI designer. Do not modify.
namespace NebliDex_Linux
{
	public partial class DepositWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label2;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.ComboBox Coin_Box;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.Label label3;

		private global::Gtk.Entry Deposit_Address;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.Button Close_Button;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget NebliDex_Linux.DepositWindow
			this.WidthRequest = 370;
			this.Name = "NebliDex_Linux.DepositWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Deposit To Wallet");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.BorderWidth = ((uint)(5));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child NebliDex_Linux.DepositWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'15\'><b>Make A Deposit</b></span>");
			this.label1.UseMarkup = true;
			this.vbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(4));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Homogeneous = true;
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.Xalign = 0.8F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'14\'>Select Coin: </span>");
			this.label2.UseMarkup = true;
			this.hbox2.Add(this.label2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label2]));
			w2.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.alignment2.RightPadding = ((uint)(60));
			// Container child alignment2.Gtk.Container+ContainerChild
			this.Coin_Box = global::Gtk.ComboBox.NewText();
			this.Coin_Box.WidthRequest = 100;
			this.Coin_Box.Name = "Coin_Box";
			this.alignment2.Add(this.Coin_Box);
			this.hbox2.Add(this.alignment2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.alignment2]));
			w4.Position = 1;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			w5.Padding = ((uint)(10));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator1]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			w6.Padding = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'14\'>Deposit Address: </span>");
			this.label3.UseMarkup = true;
			this.vbox1.Add(this.label3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label3]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			w7.Padding = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.Deposit_Address = new global::Gtk.Entry();
			this.Deposit_Address.CanFocus = true;
			this.Deposit_Address.Name = "Deposit_Address";
			this.Deposit_Address.IsEditable = false;
			this.Deposit_Address.InvisibleChar = '•';
			this.vbox1.Add(this.Deposit_Address);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.Deposit_Address]));
			w8.Position = 4;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(100));
			this.alignment1.TopPadding = ((uint)(15));
			this.alignment1.RightPadding = ((uint)(100));
			this.alignment1.BottomPadding = ((uint)(5));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.Close_Button = new global::Gtk.Button();
			this.Close_Button.CanFocus = true;
			this.Close_Button.Name = "Close_Button";
			this.Close_Button.UseUnderline = true;
			this.Close_Button.Label = global::Mono.Unix.Catalog.GetString("Close");
			this.alignment1.Add(this.Close_Button);
			this.vbox1.Add(this.alignment1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.alignment1]));
			w10.Position = 5;
			w10.Expand = false;
			w10.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
