
// This file has been generated by the GUI designer. Do not modify.
namespace NebliDex_Linux
{
	public partial class SeedListWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label2;

		private global::Gtk.Entry DNS_Field;

		private global::Gtk.Button Reset_Button;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label3;

		private global::Gtk.Entry IP_Field;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.Button Connect_Button;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget NebliDex_Linux.SeedListWindow
			this.WidthRequest = 350;
			this.Name = "NebliDex_Linux.SeedListWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Select DNS Seed");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			this.BorderWidth = ((uint)(15));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child NebliDex_Linux.SeedListWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Seed</b>");
			this.label2.UseMarkup = true;
			this.hbox1.Add(this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.DNS_Field = new global::Gtk.Entry();
			this.DNS_Field.WidthRequest = 230;
			this.DNS_Field.CanFocus = true;
			this.DNS_Field.Name = "DNS_Field";
			this.DNS_Field.IsEditable = true;
			this.DNS_Field.InvisibleChar = '•';
			this.hbox1.Add(this.DNS_Field);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.DNS_Field]));
			w2.Position = 1;
			w2.Padding = ((uint)(5));
			// Container child hbox1.Gtk.Box+BoxChild
			this.Reset_Button = new global::Gtk.Button();
			this.Reset_Button.WidthRequest = 60;
			this.Reset_Button.CanFocus = true;
			this.Reset_Button.Name = "Reset_Button";
			this.Reset_Button.UseUnderline = true;
			this.Reset_Button.BorderWidth = ((uint)(3));
			this.Reset_Button.Label = global::Mono.Unix.Catalog.GetString("Reset");
			this.hbox1.Add(this.Reset_Button);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.Reset_Button]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(2));
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Or a CN IP Address</b>");
			this.label1.UseMarkup = true;
			this.vbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("<b>IP</b>");
			this.label3.UseMarkup = true;
			this.hbox2.Add(this.label3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label3]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.IP_Field = new global::Gtk.Entry();
			this.IP_Field.WidthRequest = 275;
			this.IP_Field.CanFocus = true;
			this.IP_Field.Name = "IP_Field";
			this.IP_Field.IsEditable = true;
			this.IP_Field.InvisibleChar = '•';
			this.hbox2.Add(this.IP_Field);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.IP_Field]));
			w7.Position = 1;
			w7.Padding = ((uint)(5));
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			w8.Padding = ((uint)(2));
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(100));
			this.alignment1.TopPadding = ((uint)(5));
			this.alignment1.RightPadding = ((uint)(100));
			this.alignment1.BottomPadding = ((uint)(5));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.Connect_Button = new global::Gtk.Button();
			this.Connect_Button.CanFocus = true;
			this.Connect_Button.Name = "Connect_Button";
			this.Connect_Button.UseUnderline = true;
			this.Connect_Button.Label = global::Mono.Unix.Catalog.GetString("Connect");
			this.alignment1.Add(this.Connect_Button);
			this.vbox1.Add(this.alignment1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.alignment1]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
