
// This file has been generated by the GUI designer. Do not modify.
namespace NebliDex_Linux
{
	public partial class IntroWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Image Banner;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.Label Intro_Status_Private;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget NebliDex_Linux.IntroWindow
			this.WidthRequest = 380;
			this.HeightRequest = 139;
			this.Name = "NebliDex_Linux.IntroWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("NebliDex");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource("NebliDex_Linux.logo.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultWidth = 175;
			this.DefaultHeight = 300;
			// Container child NebliDex_Linux.IntroWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			// Container child vbox1.Gtk.Box+BoxChild
			this.Banner = new global::Gtk.Image();
			this.Banner.WidthRequest = 380;
			this.Banner.Name = "Banner";
			this.vbox1.Add(this.Banner);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.Banner]));
			w1.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.Intro_Status_Private = new global::Gtk.Label();
			this.Intro_Status_Private.HeightRequest = 20;
			this.Intro_Status_Private.Name = "Intro_Status_Private";
			this.Intro_Status_Private.LabelProp = global::Mono.Unix.Catalog.GetString("Initializing...");
			this.alignment1.Add(this.Intro_Status_Private);
			this.vbox1.Add(this.alignment1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.alignment1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			w3.Padding = ((uint)(5));
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
		}
	}
}
