
// This file has been generated by the GUI designer. Do not modify.
namespace NebliDex_Linux
{
	public partial class WithdrawWindow
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label2;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.ComboBox Coin_Box;

		private global::Gtk.HSeparator hseparator2;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label3;

		private global::Gtk.Label Balance_Amount;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label4;

		private global::Gtk.Entry Amount_Input;

		private global::Gtk.HSeparator hseparator3;

		private global::Gtk.Label label5;

		private global::Gtk.Alignment alignment3;

		private global::Gtk.Entry Destination;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.Button Withdraw_Button;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget NebliDex_Linux.WithdrawWindow
			this.WidthRequest = 370;
			this.Name = "NebliDex_Linux.WithdrawWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Withdraw From Wallet");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.BorderWidth = ((uint)(5));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child NebliDex_Linux.WithdrawWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(5));
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'15\'><b>Withdraw Funds</b></span>");
			this.label1.UseMarkup = true;
			this.vbox2.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Homogeneous = true;
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.Xalign = 0.8F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'14\'>Select Coin: </span>");
			this.label2.UseMarkup = true;
			this.hbox4.Add(this.label2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label2]));
			w2.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.alignment2.RightPadding = ((uint)(60));
			// Container child alignment2.Gtk.Container+ContainerChild
			this.Coin_Box = global::Gtk.ComboBox.NewText();
			this.Coin_Box.WidthRequest = 100;
			this.Coin_Box.Name = "Coin_Box";
			this.alignment2.Add(this.Coin_Box);
			this.hbox4.Add(this.alignment2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.alignment2]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox2.Add(this.hbox4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			w5.Padding = ((uint)(5));
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator();
			this.hseparator2.Name = "hseparator2";
			this.vbox2.Add(this.hseparator2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator2]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			w6.Padding = ((uint)(5));
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Homogeneous = true;
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'14\'>Balance:</span>");
			this.label3.UseMarkup = true;
			this.hbox5.Add(this.label3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label3]));
			w7.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.Balance_Amount = new global::Gtk.Label();
			this.Balance_Amount.Name = "Balance_Amount";
			this.Balance_Amount.Xalign = 1F;
			this.Balance_Amount.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'14\'><b>40 NEBL</b></span>");
			this.Balance_Amount.UseMarkup = true;
			this.hbox5.Add(this.Balance_Amount);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.Balance_Amount]));
			w8.Position = 1;
			this.vbox2.Add(this.hbox5);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox5]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			w9.Padding = ((uint)(5));
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'14\'>Amount:</span>");
			this.label4.UseMarkup = true;
			this.hbox6.Add(this.label4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label4]));
			w10.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.Amount_Input = new global::Gtk.Entry();
			this.Amount_Input.WidthRequest = 150;
			this.Amount_Input.CanFocus = true;
			this.Amount_Input.Name = "Amount_Input";
			this.Amount_Input.IsEditable = true;
			this.Amount_Input.InvisibleChar = '•';
			this.Amount_Input.Xalign = 1F;
			this.hbox6.Add(this.Amount_Input);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.Amount_Input]));
			w11.Position = 1;
			this.vbox2.Add(this.hbox6);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox6]));
			w12.Position = 4;
			w12.Expand = false;
			w12.Fill = false;
			w12.Padding = ((uint)(5));
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator();
			this.hseparator3.Name = "hseparator3";
			this.vbox2.Add(this.hseparator3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator3]));
			w13.Position = 5;
			w13.Expand = false;
			w13.Fill = false;
			w13.Padding = ((uint)(5));
			// Container child vbox2.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'14\'>Destination Address:</span>");
			this.label5.UseMarkup = true;
			this.vbox2.Add(this.label5);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label5]));
			w14.Position = 6;
			w14.Expand = false;
			w14.Fill = false;
			w14.Padding = ((uint)(5));
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.alignment3.LeftPadding = ((uint)(25));
			this.alignment3.RightPadding = ((uint)(25));
			// Container child alignment3.Gtk.Container+ContainerChild
			this.Destination = new global::Gtk.Entry();
			this.Destination.CanFocus = true;
			this.Destination.Name = "Destination";
			this.Destination.IsEditable = true;
			this.Destination.InvisibleChar = '•';
			this.alignment3.Add(this.Destination);
			this.vbox2.Add(this.alignment3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment3]));
			w16.Position = 7;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(100));
			this.alignment1.TopPadding = ((uint)(15));
			this.alignment1.RightPadding = ((uint)(100));
			this.alignment1.BottomPadding = ((uint)(5));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.Withdraw_Button = new global::Gtk.Button();
			this.Withdraw_Button.CanFocus = true;
			this.Withdraw_Button.Name = "Withdraw_Button";
			this.Withdraw_Button.UseUnderline = true;
			this.Withdraw_Button.Label = global::Mono.Unix.Catalog.GetString("Withdraw");
			this.alignment1.Add(this.Withdraw_Button);
			this.vbox2.Add(this.alignment1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment1]));
			w18.Position = 8;
			w18.Expand = false;
			w18.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 340;
			this.Show();
		}
	}
}
