
// This file has been generated by the GUI designer. Do not modify.
namespace NebliDex_Linux
{
	public partial class MatchOrderWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Label Header;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label Order_Type;

		private global::Gtk.Label Order_Amount;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label Order_Min_Header;

		private global::Gtk.Label Order_Min_Amount;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label Order_Min_Header1;

		private global::Gtk.Label Price;

		private global::Gtk.HSeparator hseparator3;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label My_Amount_Header;

		private global::Gtk.Entry My_Amount;

		private global::Gtk.HSeparator hseparator4;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Label Total_Cost_Header;

		private global::Gtk.Entry Total_Amount;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Label label7;

		private global::Gtk.Label My_Balance;

		private global::Gtk.HSeparator hseparator5;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.Button Match_Button;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget NebliDex_Linux.MatchOrderWindow
			this.WidthRequest = 400;
			this.Name = "NebliDex_Linux.MatchOrderWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Match Order");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(5));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child NebliDex_Linux.MatchOrderWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.Header = new global::Gtk.Label();
			this.Header.Name = "Header";
			this.Header.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'18\'><b>Sell Order Details</b></span>");
			this.Header.UseMarkup = true;
			this.vbox1.Add(this.Header);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.Header]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Homogeneous = true;
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.Order_Type = new global::Gtk.Label();
			this.Order_Type.Name = "Order_Type";
			this.Order_Type.Xalign = 0F;
			this.Order_Type.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'12\'>Available:</span>");
			this.Order_Type.UseMarkup = true;
			this.hbox5.Add(this.Order_Type);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.Order_Type]));
			w2.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.Order_Amount = new global::Gtk.Label();
			this.Order_Amount.Name = "Order_Amount";
			this.Order_Amount.Xalign = 1F;
			this.Order_Amount.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'12\'><b>40 NEBL</b></span>");
			this.Order_Amount.UseMarkup = true;
			this.hbox5.Add(this.Order_Amount);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.Order_Amount]));
			w3.Position = 1;
			this.vbox1.Add(this.hbox5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Homogeneous = true;
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.Order_Min_Header = new global::Gtk.Label();
			this.Order_Min_Header.Name = "Order_Min_Header";
			this.Order_Min_Header.Xalign = 0F;
			this.Order_Min_Header.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'12\'>Minimum:</span>");
			this.Order_Min_Header.UseMarkup = true;
			this.hbox6.Add(this.Order_Min_Header);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.Order_Min_Header]));
			w5.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.Order_Min_Amount = new global::Gtk.Label();
			this.Order_Min_Amount.Name = "Order_Min_Amount";
			this.Order_Min_Amount.Xalign = 1F;
			this.Order_Min_Amount.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'12\'><b>10 NEBL</b></span>");
			this.Order_Min_Amount.UseMarkup = true;
			this.hbox6.Add(this.Order_Min_Amount);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.Order_Min_Amount]));
			w6.Position = 1;
			this.vbox1.Add(this.hbox6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox6]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			w7.Padding = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Homogeneous = true;
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.Order_Min_Header1 = new global::Gtk.Label();
			this.Order_Min_Header1.Name = "Order_Min_Header1";
			this.Order_Min_Header1.Xalign = 0F;
			this.Order_Min_Header1.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'12\'>Price:</span>");
			this.Order_Min_Header1.UseMarkup = true;
			this.hbox7.Add(this.Order_Min_Header1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.Order_Min_Header1]));
			w8.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.Price = new global::Gtk.Label();
			this.Price.Name = "Price";
			this.Price.Xalign = 1F;
			this.Price.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'12\'><b>0.000456 BTC</b></span>");
			this.Price.UseMarkup = true;
			this.hbox7.Add(this.Price);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.Price]));
			w9.Position = 1;
			this.vbox1.Add(this.hbox7);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox7]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			w10.Padding = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator();
			this.hseparator3.Name = "hseparator3";
			this.vbox1.Add(this.hseparator3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator3]));
			w11.Position = 4;
			w11.Expand = false;
			w11.Fill = false;
			w11.Padding = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Homogeneous = true;
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.My_Amount_Header = new global::Gtk.Label();
			this.My_Amount_Header.Name = "My_Amount_Header";
			this.My_Amount_Header.Xalign = 0F;
			this.My_Amount_Header.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'11\'>Amount (NEBL):</span>");
			this.My_Amount_Header.UseMarkup = true;
			this.hbox8.Add(this.My_Amount_Header);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.My_Amount_Header]));
			w12.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.My_Amount = new global::Gtk.Entry();
			this.My_Amount.WidthRequest = 150;
			this.My_Amount.CanFocus = true;
			this.My_Amount.Name = "My_Amount";
			this.My_Amount.IsEditable = true;
			this.My_Amount.InvisibleChar = '•';
			this.My_Amount.Xalign = 1F;
			this.hbox8.Add(this.My_Amount);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.My_Amount]));
			w13.Position = 1;
			this.vbox1.Add(this.hbox8);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox8]));
			w14.Position = 5;
			w14.Expand = false;
			w14.Fill = false;
			w14.Padding = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator4 = new global::Gtk.HSeparator();
			this.hseparator4.Name = "hseparator4";
			this.vbox1.Add(this.hseparator4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator4]));
			w15.Position = 6;
			w15.Expand = false;
			w15.Fill = false;
			w15.Padding = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Homogeneous = true;
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.Total_Cost_Header = new global::Gtk.Label();
			this.Total_Cost_Header.Name = "Total_Cost_Header";
			this.Total_Cost_Header.Xalign = 0F;
			this.Total_Cost_Header.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'11\'>Total Cost (BTC):</span>");
			this.Total_Cost_Header.UseMarkup = true;
			this.hbox9.Add(this.Total_Cost_Header);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.Total_Cost_Header]));
			w16.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.Total_Amount = new global::Gtk.Entry();
			this.Total_Amount.WidthRequest = 150;
			this.Total_Amount.CanFocus = true;
			this.Total_Amount.Name = "Total_Amount";
			this.Total_Amount.IsEditable = true;
			this.Total_Amount.InvisibleChar = '•';
			this.Total_Amount.Xalign = 1F;
			this.hbox9.Add(this.Total_Amount);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.Total_Amount]));
			w17.Position = 1;
			this.vbox1.Add(this.hbox9);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox9]));
			w18.Position = 7;
			w18.Expand = false;
			w18.Fill = false;
			w18.Padding = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Homogeneous = true;
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'11\'>My Balance:</span>");
			this.label7.UseMarkup = true;
			this.hbox10.Add(this.label7);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label7]));
			w19.Position = 0;
			// Container child hbox10.Gtk.Box+BoxChild
			this.My_Balance = new global::Gtk.Label();
			this.My_Balance.Name = "My_Balance";
			this.My_Balance.Xalign = 1F;
			this.My_Balance.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\'11\'><b>40 BTC</b></span>");
			this.My_Balance.UseMarkup = true;
			this.hbox10.Add(this.My_Balance);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.My_Balance]));
			w20.Position = 1;
			this.vbox1.Add(this.hbox10);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox10]));
			w21.Position = 8;
			w21.Expand = false;
			w21.Fill = false;
			w21.Padding = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator5 = new global::Gtk.HSeparator();
			this.hseparator5.Name = "hseparator5";
			this.vbox1.Add(this.hseparator5);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator5]));
			w22.Position = 9;
			w22.Expand = false;
			w22.Fill = false;
			w22.Padding = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(100));
			this.alignment1.RightPadding = ((uint)(100));
			this.alignment1.BottomPadding = ((uint)(5));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.Match_Button = new global::Gtk.Button();
			this.Match_Button.CanFocus = true;
			this.Match_Button.Name = "Match_Button";
			this.Match_Button.UseUnderline = true;
			this.Match_Button.Label = global::Mono.Unix.Catalog.GetString("Match");
			this.alignment1.Add(this.Match_Button);
			this.vbox1.Add(this.alignment1);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.alignment1]));
			w24.Position = 10;
			w24.Expand = false;
			w24.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 366;
			this.Show();
		}
	}
}
